steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/crucial-oven-404213/porosartapi', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/crucial-oven-404213/porosartapi']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'porosart-api', '--image', 'gcr.io/crucial-oven-404213/porosartapi', '--region', 'us-central1']
images:
- gcr.io/crucial-oven-404213/porosartapi