# Cloud builder for the dotnet builder.

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/porosart-api-c46jphp5cq-uc/dotnet'
  - '.'

# Build the test projects
- name: 'gcr.io/porosart-api-c46jphp5cq-uc/dotnet'
  args: ['build']
  dir: 'porosartapi'

- name: 'gcr.io/porosart-api-c46jphp5cq-uc/dotnet'
  args: ['build']
  dir: 'porosartapi'

# Specify the --no-source flag to indicate that no source code should be uploaded
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', '--config=cloudbuild.yaml', '--no-source']

images:
- 'gcr.io/porosart-api-c46jphp5cq-uc/dotnet'

